### ISSUE TITLE
Put the Code In the Repo!

### ISSUE THREAD

**Issue by Preciousomonze** [Preciousomonze/woo-cart-standalone-force-sell-sorting#1]
Hacktoberfest drill, didn't have time to actually sort my repo and use it for hacktoberfest period, so i got this.
At least it's a project, so let me just make use of it.
An open project 😸

**Comment by Mastersam07** [comment]
Boss 🙇 🙇 🙇

**Comment by Preciousomonze** [comment]
Boss, no dey whine naw -_-

**Comment by Mastersam07** [comment]
No sir 🙇 🙇 🙇
